### PR TITLE
Updated the requirements with new versions.

### PR DESCRIPTION
**Pull request by sasanikolic90**

### CODE REVIEW

**Comment by bhasselbeck** [comment]
I can vouch for this.  I ran into a PHP 7.0 issue as well during the playbook install.  Fixing to these versions fixed the problem.

**Comment by bhasselbeck** [comment]
Anyway we can merge this?

**Comment by geerlingguy** [comment]
@bhasselbeck - I've updated the defaults so they work with the latest role versions (my intention is that this project will always work with latest; it's not quite on the same stability track as Drupal VM is... but maybe it should be :/).

**Comment by geerlingguy** [comment]
(Note that I also added automated tests and set them to run at least 1x/week on Travis CI: https://travis-ci.org/geerlingguy/drupal-pi).

**Pull request closed without merging**
